[versions]
agp = "8.12.3"
android-compileSdk = "36"
android-minSdk = "23"
android-targetSdk = "36"
androidx-activity = "1.11.0"
androidx-lifecycle = "2.9.6"
composeHotReload = "1.0.0-rc03"
composeMultiplatform = "1.9.3"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"

# DataStore
androidx-datastore = "1.1.7"

# Compose Navigation
navi-compose = "2.9.1"
androidx-navigation = "2.9.6"

# Window Manager
androidx-window = "1.5.0-rc01"

room = "2.8.3"
sqlite = "2.6.1"
ksp = "2.2.21-2.0.4"

coil = "3.3.0"
ktor = "3.3.2"

compottie = "2.0.2"

ui-backhandler = "1.10.0-beta01"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# DataStore
androidx-datastore-core = { module = "androidx.datastore:datastore", version.ref = "androidx-datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

# Compose Navigation
navi-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navi-compose" }
navi-runtime = { module = "org.jetbrains.androidx.navigation:navigation-runtime", version.ref = "navi-compose" }
navi-common = { module = "org.jetbrains.androidx.navigation:navigation-common", version.ref = "navi-compose" }

# Window Manager
androidx-window = { module = "org.jetbrains.androidx.window:window-core", version.ref = "androidx-window" }

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Optional SQLite Wrapper available in version 2.8.0 and higher
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }

coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Lottie: https://github.com/alexzhirkevich/compottie
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }

navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "ui-backhandler" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
