package io.github.lumkit.pline.ui.theme.color

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class AppColorScheme(
    val primary: Color,
    val secondary: Color,
    val background: Color,
    val surface: Color,
    val secondarySurface: Color,
    val primaryContainer: Color,
    val secondaryContainer: Color,
    val text: Color,
    val error: Color,
    val warning: Color,
    val success: Color,
    val onPrimary: Color,
    val onSecondary: Color,
    val onBackground: Color,
    val onSurface: Color,
    val onSecondarySurface: Color,
    val onPrimaryContainer: Color,
    val onSecondaryContainer: Color,
    val onText: Color,
    val onError: Color,
    val onWarning: Color,
    val onSuccess: Color,
)

fun lightAppColorScheme(
    primary: Color = Color(0xFF3FA162),
    secondary: Color = Color(0xFFFFA063),
    background: Color = Color(0xFFFFFFFF),
    surface: Color = Color(0xFFFFFFFF),
    secondarySurface: Color = Color(0xFFF5F5F5),
    primaryContainer: Color = Color(0xFFE0F5E7),
    secondaryContainer: Color = Color(0xFFFEF2E0),
    text: Color = Color(0xFF1F1F39),
    error: Color = Color(0xFFB00020),
    warning: Color = Color(0xFFF57F17),
    success: Color = Color(0xFF4CAF50),
    onPrimary: Color = Color(0xFF1B5E33),
    onSecondary: Color = Color(0xFFB66A3F),
    onBackground: Color = Color(0xFF121212),
    onSurface: Color = Color(0xFF121212),
    onSecondarySurface: Color = Color(0xFF1A1A1A),
    onPrimaryContainer: Color = Color(0xFF10371F),
    onSecondaryContainer: Color = Color(0xFF3B230F),
    onText: Color = Color(0xFFFFFFFF),
    onError: Color = Color(0xFF7A0018),
    onWarning: Color = Color(0xFFB36B00),
    onSuccess: Color = Color(0xFF2E7D32),
) = AppColorScheme(
    primary,
    secondary,
    background,
    surface,
    secondarySurface,
    primaryContainer,
    secondaryContainer,
    text,
    error,
    warning,
    success,
    onPrimary,
    onSecondary,
    onBackground,
    onSurface,
    onSecondarySurface,
    onPrimaryContainer,
    onSecondaryContainer,
    onText,
    onError,
    onWarning,
    onSuccess,
)

fun darkAppColorScheme(
    primary: Color = Color(0xFF66D17A),
    secondary: Color = Color(0xFFFFC08A),
    background: Color = Color(0xFF121212),
    surface: Color = Color(0xFF1E1E1E),
    secondarySurface: Color = Color(0xFF232323),
    primaryContainer: Color = Color(0xFF134826),
    secondaryContainer: Color = Color(0xFF3E2410),
    text: Color = Color(0xFFFFFFFF),
    error: Color = Color(0xFFCF6679),
    warning: Color = Color(0xFFFFB86B),
    success: Color = Color(0xFF66BB6A),
    onPrimary: Color = Color(0xFF003412),
    onSecondary: Color = Color(0xFF6F3B18),
    onBackground: Color = Color(0xFFFFFFFF),
    onSurface: Color = Color(0xFFFFFFFF),
    onSecondarySurface: Color = Color(0xFFE6E6E6),
    onPrimaryContainer: Color = Color(0xFFBFF3D0),
    onSecondaryContainer: Color = Color(0xFFF6E6CF),
    onText: Color = Color(0xFF121212),
    onError: Color = Color(0xFF7A0018),
    onWarning: Color = Color(0xFF5A3600),
    onSuccess: Color = Color(0xFF002E1A),
) = AppColorScheme(
    primary,
    secondary,
    background,
    surface,
    secondarySurface,
    primaryContainer,
    secondaryContainer,
    text,
    error,
    warning,
    success,
    onPrimary,
    onSecondary,
    onBackground,
    onSurface,
    onSecondarySurface,
    onPrimaryContainer,
    onSecondaryContainer,
    onText,
    onError,
    onWarning,
    onSuccess,
)
